// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpgtmbjykxutipytgwhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZ3RtYmp5a3h1dGlweXRnd2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDQxMzgsImV4cCI6MjA2MzYyMDEzOH0.bqm5p8TACLwLPtyyUC6hl6zeQpBco9kGy7YkwNMIAvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);